apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: global-reader
rules:
- apiGroups: [""]
  resources: ["pods", "endpoints"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: global-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  # roleRef specifies the binding to a Role / ClusterRole
  kind: ClusterRole
  name: global-reader
  apiGroup: rbac.authorization.k8s.io
